apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sample-java-app-helm-charts.fullname" . }}
  labels:
    {{- include "sample-java-app-helm-charts.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sample-java-app-helm-charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sample-java-app-helm-charts.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.cont_port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.cont_port }}
            initialDelaySeconds: 30
            periodSeconds: 3
          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.cont_port }}
            initialDelaySeconds: 30
            periodSeconds: 3 
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
